#!/usr/bin/env bash
# AUTH_MODE dispatcher (01.4 SF-2, Interface Contract 2). Runs INSIDE the agent container,
# invoked by entrypoint.sh after the home-skeleton seed. That ordering is load-bearing: the
# skeleton seed must not overwrite a credential.
#
#   bash bootstrap-auth.sh <agent>        # agent in claude | codex | agy
#
# Ships at images/bootstrap-auth.sh, not the plan's images/agent-base/bootstrap-auth.sh --
# 01.2's Deviation 1 collapsed the per-agent image directories into one multi-stage
# images/Dockerfile. See this feature plan, Deviation 1. The REASON Interface Contract 2 gives
# for the location is unchanged: the build context is ./images, so a file under scripts/ cannot
# be COPY'd in, and the copy-to-volume must run where both the :ro source and the state volume
# are mounted.
#
# EXIT CODES (Interface Contract 2) -- every one of them fails CLOSED and names its destination:
#
#   0  authenticated, or already was (idempotent re-run)
#   2  unsupported (agent, AUTH_MODE) cell, or AUTH_MODE unset. Names the cell and that
#      agent's supported set. An unsupported cell must NEVER degrade to a working-but-
#      different mode -- that would silently defeat "the default is the safest mode that
#      agent supports" (R4.12).
#   3  required credential material absent. Names what to supply; under oauth-mount at
#      steady state it names the bootstrap command to run.
#   4  precondition failed -- a required provider endpoint is refused by the mediator.
#      Names the FQDN. Mirrors R9.3/R12.2's posture at the mediator: a legitimate policy
#      gap must be distinguishable from an attack.
#
# THIS SCRIPT NEVER PRINTS CREDENTIAL MATERIAL. It asserts presence, shape and exit status.
# Every diagnostic below names a variable or a path, never a value.
set -euo pipefail

AGENT="${1-}"
MODE="${AUTH_MODE-}"

# --at-start marks the pass entrypoint.sh makes on EVERY container start, as opposed to the
# operator's explicit one-shot invocation. The two differ in one way only: what an ABSENT
# CREDENTIAL means (operator decision, 2026-09-07 -- see this feature plan, Deviation 2).
#
#   at start   a missing credential WARNS and the container starts. It is not yet a failure:
#              oauth-interactive obtains its credential from a later interactive invocation,
#              and blocking here would stop the pod coming up at all on a fresh volume --
#              including under the default profile, whose claude and codex cells are
#              oauth-interactive and whose agy cell is apikey with no key wired by Compose.
#   explicit   a missing credential is exit 3, and oauth-interactive actually runs the login.
#
# What does NOT relax at start: an unset or unsupported AUTH_MODE is exit 2 in both passes.
# That is a misconfiguration rather than a not-yet-done step, and it fails closed either way.
# oauth-mount also does not relax -- criterion 5 requires that an agent which deletes its own
# credential FAILS ITS NEXT START rather than triggering a silent re-copy.
AT_START=0
[ "${2-}" = "--at-start" ] && AT_START=1

die() { echo "bootstrap-auth: $2" >&2; exit "$1"; }

# Absent credential: fatal on an explicit invocation, a warning during the start-time pass.
missing_credential() {
  if [ "$AT_START" -eq 1 ]; then
    echo "bootstrap-auth: WARNING -- $1" >&2
    echo "bootstrap-auth: ($AGENT, $MODE) is NOT authenticated; the container is starting anyway." >&2
    exit 0
  fi
  die 3 "$1"
}

# --------------------------------------------------------------------------- matrix
# Interface Contract 1, the authoritative support matrix. SEVEN supported cells.
# `agy` is apikey-only BY DECISION (D9), not by omission: an agy OAuth relationship reopens
# the Antigravity ToS question the PRD carries as unresolved and R5.13 permanently bars
# interception for. R4.12 requires an API-key OR an OAuth configuration per agent, not both.
supported_modes_for() {
  case "$1" in
    claude) echo "apikey oauth-interactive oauth-token" ;;
    codex)  echo "apikey oauth-interactive oauth-mount" ;;
    agy)    echo "apikey" ;;
    *)      echo "" ;;
  esac
}

# Provider authentication endpoints, per agent, probed before an OAuth flow starts.
#
# These are OBSERVATION-DERIVED and provisional on the same terms as policy/allowlist.base.yaml
# (R5.8, D17): running the flow IS the observation of the minimal destination set, and the
# mediator's own audit line for a blocked attempt is the independent second source D17 requires.
# Do not extend this list from a vendor reference page -- that is precisely what R5.8 forbids.
# Update it, and allowlist.base.yaml, from what a real flow was seen to need.
#
# KEEP THIS LIST TO ENDPOINTS THE FLOW IS KNOWN TO NEED. The probe is itself traffic: every host
# named here produces an audit line whether or not the login ever touches it, and an `allow` line
# generated by this check reads exactly like evidence that the flow required the host. Probing a
# guess therefore MANUFACTURES the corroboration D17 asks for, which is the failure R5.8 exists to
# prevent. Observed at the first SF-2 login run: claude.ai and console.anthropic.com were probed
# here, logged `allow`, and were never touched by the flow itself.
auth_endpoints_for() {
  case "$1" in
    # platform.claude.com: Claude Code fails startup without it, cross-validated against the
    # mediator's own denial line. api.anthropic.com: the API host, allowlisted since 01.1.
    claude) echo "platform.claude.com api.anthropic.com" ;;
    codex)  echo "auth.openai.com chatgpt.com api.openai.com" ;;
    *)      echo "" ;;
  esac
}

# --------------------------------------------------------------------------- argument gate
case "$AGENT" in
  claude|codex|agy) ;;
  "") die 2 "no agent given. usage: bash bootstrap-auth.sh <claude|codex|agy>" ;;
  *)  die 2 "unknown agent '$AGENT'. usage: bash bootstrap-auth.sh <claude|codex|agy>" ;;
esac

# AUTH_MODE has NO default in the image (Interface Contract 2). An unset value is an error,
# not a fallback -- a default here would pick a mode on the operator's behalf and could pick a
# less safe one than R4.12 mandates.
[ -n "$MODE" ] || die 2 "AUTH_MODE is unset for '$AGENT'. Supported: $(supported_modes_for "$AGENT"). \
Compose sets it per agent from the profile's auth_mode block."

if ! echo " $(supported_modes_for "$AGENT") " | grep -q " $MODE "; then
  die 2 "unsupported cell ($AGENT, $MODE). '$AGENT' supports: $(supported_modes_for "$AGENT"). \
Refusing to fall back to another mode -- see Interface Contract 1."
fi

# --------------------------------------------------------------------------- 01.2 contract
# ASSERTED, never set (Interface Contract 5). 01.2 owns these; 01.4 sits on top of them. If
# they are wrong, the credential this script is about to write lands somewhere that does not
# survive a restart, and that failure is far cheaper to catch here than at T9.
[ "${HOME-}" = "/home/agent" ] || die 3 "HOME is '${HOME-<unset>}', expected /home/agent (01.2 Interface Contract 2)"
case "$AGENT" in
  claude) [ "${CLAUDE_CONFIG_DIR-}" = "/home/agent/.claude" ] \
            || die 3 "CLAUDE_CONFIG_DIR is '${CLAUDE_CONFIG_DIR-<unset>}', expected /home/agent/.claude" ;;
  codex)  [ "${CODEX_HOME-}" = "/home/agent/.codex" ] \
            || die 3 "CODEX_HOME is '${CODEX_HOME-<unset>}', expected /home/agent/.codex" ;;
esac

# --------------------------------------------------------------------------- precondition
# An agent on an `internal: true` network reaches nothing except through the mediator, so an
# OAuth flow against an endpoint the mediator does not allow HANGS OR FAILS OPAQUELY (Edge
# Case 5). This turns that into a named exit before the operator is asked to open a browser.
#
# The agent container has no copy of policy/resolved/default.yaml -- the mediator reads it from
# its own image layer, and the ./images build context cannot reach policy/. So the check is a
# PROBE THROUGH THE MEDIATOR rather than a file read, which is also the stronger check: it tests
# what the enforcement point actually does, not what an artifact says it should do. The probe is
# additionally the D17 observation itself -- each refusal writes the audit line SF-2 harvests.
#
# A refused CONNECT returns Squid's ERR_MEDIATOR_ALLOWLIST page (HTTP 403). The audit line is
# the authoritative denial record and names the control; this only needs to know it was refused.
probe_endpoint() {
  local fqdn="$1" out ca ca_args=()

  # The TLS proxy hop must be ANCHORED or this check silently inverts. claude and agy reach an
  # `https://` listener; without the mediator CA, curl fails the PROXY handshake and never issues
  # CONNECT at all -- the mediator logs nothing and the probe cannot tell "refused by policy" from
  # "could not talk to the proxy". Observed: every claude candidate returned 000 with no audit
  # line until --proxy-cacert was supplied. codex's hop is plain HTTP CONNECT and needs no anchor,
  # which is why the CA variables are read rather than a path being hardcoded.
  for ca in "${NODE_EXTRA_CA_CERTS-}" "${SSL_CERT_FILE-}"; do
    if [ -n "$ca" ] && [ -r "$ca" ]; then ca_args=(--proxy-cacert "$ca"); break; fi
  done

  # A refused CONNECT is reported on STDERR, not in %{http_code} -- curl exits 56 and the code is
  # 000, the same 000 a transport failure produces. Matching on the message is what distinguishes
  # a policy denial from an unreachable proxy; matching on the code would treat both as failures
  # and exit 4 on a broken pod. Both curl phrasings are accepted across versions.
  out="$(curl -sS -o /dev/null ${ca_args[@]+"${ca_args[@]}"} --max-time 20 "https://$fqdn/" 2>&1)" || true
  case "$out" in
    *"CONNECT tunnel failed, response 403"*)   return 1 ;;
    *"received HTTP code 403 from proxy"*)     return 1 ;;
    *"Received HTTP code 403 from proxy"*)     return 1 ;;
    *) return 0 ;;
  esac
}

check_auth_endpoints() {
  local fqdn
  for fqdn in $(auth_endpoints_for "$AGENT"); do
    if ! probe_endpoint "$fqdn"; then
      die 4 "provider endpoint '$fqdn' is refused by the mediator, so ($AGENT, $MODE) cannot \
complete. Add it to policy/allowlist.base.yaml, then: bash scripts/compile-policy.sh && \
docker compose build egress-mediator. NOTE: an allowlist edit is inert until BOTH run -- the \
mediator reads its policy from its own image layer. The audit line for this attempt is the \
authoritative denial record."
    fi
  done
}

# --------------------------------------------------------------------------- idempotency
# "Authenticated, or already was" (exit 0). Presence and shape only -- never content.
already_authenticated() {
  case "$AGENT" in
    claude)
      [ -s "$CLAUDE_CONFIG_DIR/.credentials.json" ] || [ -s "$HOME/.claude.json" ]
      ;;
    codex)
      # SHAPE, not just presence (edge case 11): a bootstrap interrupted mid-copy, or an
      # auth.json holding only OPENAI_API_KEY, must not read as authenticated -- this test
      # short-circuits the whole branch, so a partial state here would skip the login under
      # oauth-interactive and skip the copy under oauth-mount. grep rather than jq: only the
      # agy image carries jq.
      [ -s "$CODEX_HOME/auth.json" ] && grep -q '"refresh_token"' "$CODEX_HOME/auth.json"
      ;;
    agy)
      # agy's apikey cell is env-delivered: the credential is not persisted, so "already
      # authenticated" is only ever about the settings half (see the agy branch).
      return 1
      ;;
  esac
}

# --------------------------------------------------------------------------- mode branches
do_apikey() {
  local var
  case "$AGENT" in
    claude) var=ANTHROPIC_API_KEY ;;
    codex)  var=OPENAI_API_KEY ;;
    agy)    var=GEMINI_API_KEY ;;
  esac
  [ -n "${!var-}" ] || missing_credential "AUTH_MODE=apikey requires $var in the environment for \
'$AGENT'. Supply it via the Compose environment (references/.env_keys is git-ignored and holds \
the keys)."

  if [ "$AGENT" = "agy" ]; then
    # D9 / Interface Contract 1: the env var ALONE is a documented no-op for agy. The settings
    # file must also select the provider, so this branch writes that and nothing else -- the
    # key itself stays in the environment and is never persisted to the volume.
    local settings="$HOME/.gemini/settings.json"
    mkdir -p "$HOME/.gemini"
    if [ -s "$settings" ] && grep -q '"modelProvider"[[:space:]]*:[[:space:]]*"gemini"' "$settings"; then
      echo "bootstrap-auth: agy already selects modelProvider=gemini"
    elif [ -s "$settings" ]; then
      missing_credential "$settings exists but does not set \"modelProvider\": \"gemini\". \
Refusing to rewrite an existing settings file -- edit it, or remove it and re-run."
    else
      printf '%s\n' '{' '  "modelProvider": "gemini"' '}' > "$settings"
      echo "bootstrap-auth: wrote modelProvider=gemini to \$HOME/.gemini/settings.json"
    fi
  fi

  echo "bootstrap-auth: ($AGENT, apikey) ready -- credential supplied by environment ($var set)"
}

do_oauth_interactive() {
  if already_authenticated; then
    echo "bootstrap-auth: ($AGENT, oauth-interactive) already authenticated -- no-op"
    return 0
  fi

  # At start there is no TTY and no operator watching, so this pass reports the state and stops.
  # The login below is reached only by an explicit invocation.
  if [ "$AT_START" -eq 1 ]; then
    echo "bootstrap-auth: WARNING -- (claude|codex, oauth-interactive) has no credential yet." >&2
    echo "bootstrap-auth: authenticate with:  docker compose ... run --rm $AGENT bash /usr/local/bin/bootstrap-auth $AGENT" >&2
    exit 0
  fi

  check_auth_endpoints

  # R4.9's headless definition is "paste-back, device code, or a pre-minted token", and requires
  # only that NO BROWSER EXIST INSIDE THE CONTAINER. This path is paste-back: the agent's own CLI
  # prints a URL, the operator opens it on the HOST and pastes the code back. An interactive
  # terminal is permitted -- see criterion 4 and the T24 amendment.
  echo "bootstrap-auth: ($AGENT, oauth-interactive) starting paste-back login."
  echo "bootstrap-auth: open the printed URL on the HOST; no browser exists in this container."

  case "$AGENT" in
    claude) claude /login ;;
    # --device-auth is REQUIRED here, not a preference. Plain `codex login` starts a callback
    # server on localhost:1455 INSIDE the container and hands the browser a
    # redirect_uri of http://localhost:1455/auth/callback. The operator's browser runs on the
    # HOST, where that port is nothing -- the pod publishes no ports (R2.8 default-off) and the
    # agent networks are `internal: true`. The flow completes at the provider and then strands on
    # a callback that can never arrive; codex itself says "On a remote or headless machine? Use
    # `codex login --device-auth` instead." Device code is one of the three paths R4.9 enumerates
    # as headless, and it needs no published port at all.
    #
    # The callback-forward alternative (publish 127.0.0.1:1455:1455, fallback 1457) is documented
    # and ships as a layerable fragment for operators who want it -- it is not the default,
    # because opening a host port the headless path does not need is the wrong default under R2.8.
    codex)  codex login --device-auth ;;
  esac

  already_authenticated \
    || die 3 "($AGENT, oauth-interactive) did not produce a credential on the state volume. \
Re-run the login; if it keeps failing, check the mediator audit log for a refused endpoint."
  echo "bootstrap-auth: ($AGENT, oauth-interactive) authenticated"
}

do_oauth_token() {
  # claude only. `claude setup-token` mints a ONE-YEAR CLAUDE_CODE_OAUTH_TOKEN -- the R4.16 risk
  # this feature records in docs/records/credential-inventory.md, and the reason SF-5 revokes the
  # test credential at feature close rather than leaving a year-long token outstanding.
  [ -n "${CLAUDE_CODE_OAUTH_TOKEN-}" ] || missing_credential "AUTH_MODE=oauth-token requires \
CLAUDE_CODE_OAUTH_TOKEN in the environment. Mint one on the HOST with 'claude setup-token' -- it \
is valid for ONE YEAR (R4.16); record it in docs/records/credential-inventory.md and revoke it \
when it is no longer needed."
  echo "bootstrap-auth: (claude, oauth-token) ready -- pre-minted token supplied by environment"
}

do_oauth_mount() {
  # codex only -- the matrix has no other supported cell (claude's host credential is
  # macOS-Keychain-resident and not portable to a Linux container, R4.8; agy offers no OAuth
  # cell at all, D9).
  #
  # THE BOOTSTRAP BOUNDARY IS THE MOUNT, NOT A FLAG (R4.15, criterion 5). $SRC exists only while
  # compose/overrides/oauth-mount.bootstrap.yaml is layered, which is the one-shot `run --rm`
  # and nothing else. So at steady state there is no source to copy from, and two failures stop
  # being possible rather than being guarded against: a re-copy on every start clobbering the
  # token the container just refreshed (edge case 1), and an agent DELETING its own credential
  # to force a re-copy (edge case 2), where the guard's condition would be exactly what the
  # agent controls. An emptied volume exits 3 here and -- because entrypoint.sh runs under
  # `set -e` -- FAILS THE CONTAINER START.
  #
  # This branch does NOT relax at --at-start. `missing_credential` is deliberately not used
  # below: every exit here is die 3.
  local src="${OAUTH_MOUNT_SRC:-/run/oauth-src}"

  if already_authenticated; then
    echo "bootstrap-auth: (codex, oauth-mount) already authenticated -- no-op"
    return 0
  fi

  local bootstrap_cmd="bash scripts/stage-oauth-mount.sh --profile oauth-mount && \
docker compose --env-file compose/pins.env -f compose/compose.yaml \
-f compose/overrides/default.yaml -f compose/overrides/oauth-mount.bootstrap.yaml \
run --rm codex bash /usr/local/bin/bootstrap-auth codex"

  [ -d "$src" ] || die 3 "(codex, oauth-mount) has no credential on the state volume and no \
credential source at $src -- this is steady state, where R4.15 requires the host mount to be \
ABSENT. Re-bootstrap deliberately: $bootstrap_cmd"

  # :ro is the ONLY real control here (R4.13). Docker Desktop's VirtioFS fakes file ownership,
  # so a 0600 on the host means nothing inside the container -- the mount mode is what is
  # asserted, and it is read from the kernel's own view rather than trusted from the fragment.
  # Field 6 of a mountinfo line is the per-mount option list; field 5 is the mount point.
  local opts
  opts="$(awk -v mp="$src" '$5 == mp {print $6}' /proc/self/mountinfo | tail -n1)"
  [ -n "$opts" ] || die 3 "$src is not a mount point. R4.14 requires a dedicated :ro DIRECTORY \
mounted from the host, not a directory the container created for itself."
  case ",$opts," in
    *,ro,*) ;;
    *) die 3 "$src is mounted '$opts', not read-only. R4.13 permits :ro and nothing else -- a \
writable credential source lets a compromised agent write back to the host." ;;
  esac

  # R4.17: the risk record travels WITH the material it is about. scripts/stage-oauth-mount.sh
  # writes it from the profile's oauth_mount.codex.accepted_risk block, so a credential can only
  # be staged by an operator who recorded what staging it costs. 01.5 moves the same refusal to
  # build time (T27); this is the bootstrap-time half Interface Contract 3 assigns to 01.4.
  local risk="$src/accepted-risk.yaml"
  [ -s "$risk" ] || die 3 "$src carries no accepted-risk.yaml. R4.17 requires the accepted risk \
to be recorded before a host credential crosses the boundary. Stage the directory with \
scripts/stage-oauth-mount.sh rather than by hand -- it writes the record from the profile."
  local field
  for field in file mount_mode revocation_path blast_radius rotation; do
    grep -Eq "^[[:space:]]*${field}:" "$risk" \
      || die 3 "$risk is missing the '$field' field (R4.17). Re-run scripts/stage-oauth-mount.sh."
  done

  local staged="$src/auth.json"
  [ -s "$staged" ] || die 3 "$src is mounted but holds no auth.json. Run \
'bash scripts/stage-oauth-mount.sh' on the HOST first -- it stages the credential from \
~/.codex/auth.json with OPENAI_API_KEY removed."

  # Shape, never content (edge case 11): a bootstrap interrupted mid-copy, or a directory holding
  # a config but no token, must not read as authenticated. grep rather than jq -- only the agy
  # image carries jq, and claiming a JSON parse this container cannot do would be worse than an
  # honest string check.
  grep -q '"refresh_token"' "$staged" \
    || die 3 "$staged carries no refresh_token -- it is not an OAuth credential set. A file \
holding only OPENAI_API_KEY is an API key, which is AUTH_MODE=apikey, not oauth-mount."

  # The staged copy must NOT carry OPENAI_API_KEY, and this is a TEST-VALIDITY control before it
  # is a security one: codex would authenticate off the API key and this cell would pass green
  # while the OAuth path it exists to prove was broken. The staging script strips it; this
  # refuses a hand-built directory that did not.
  ! grep -q '"OPENAI_API_KEY"' "$staged" \
    || die 3 "$staged still carries OPENAI_API_KEY. Stage with scripts/stage-oauth-mount.sh, \
which removes it -- mounted as-is, codex could authenticate off the API key and this cell would \
pass while the OAuth path was broken."

  # ONE FILE, never the directory. R4.14's dedicated directory is about what leaves the host;
  # copying only the credential is about what lands on the volume -- accepted-risk.yaml is the
  # operator's record and has no business persisting into the agent's home.
  mkdir -p "$CODEX_HOME"
  cp "$staged" "$CODEX_HOME/auth.json"
  chmod 600 "$CODEX_HOME/auth.json"

  already_authenticated \
    || die 3 "(codex, oauth-mount) copy from $src did not produce $CODEX_HOME/auth.json"

  echo "bootstrap-auth: (codex, oauth-mount) bootstrapped from $src onto the state volume"
  echo "bootstrap-auth: ONE-SHOT. codex ROLLS its refresh token (01.4 SF-3), so this container's"
  echo "bootstrap-auth: first refresh supersedes the host copy -- expect to run 'codex login' on"
  echo "bootstrap-auth: the host again. Steady state must NOT layer the bootstrap fragment."
}

# --------------------------------------------------------------------------- dispatch
case "$MODE" in
  apikey)            do_apikey ;;
  oauth-interactive) do_oauth_interactive ;;
  oauth-token)       do_oauth_token ;;
  oauth-mount)       do_oauth_mount ;;
  *)                 die 2 "unhandled AUTH_MODE '$MODE' for '$AGENT' (matrix and dispatch disagree)" ;;
esac
