#!/usr/bin/env python3
"""Regenerate the CCCS Medium catalogue from the CCCS Annex B spreadsheet.

Writes references/cccs-medium-profile.md (ID/title table for the model to read) and
assets/cccs-medium-controls.json (full definition and guidance text, read by scripts only).

Usage:
  python3 scripts/build_profile.py [xlsx-path-or-url] [output-md] [output-json]

Defaults to the official Annex B URL and the skill's own references/ and assets/ paths.
Standard library only.
"""
import json
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
import zipfile
from collections import OrderedDict
from io import BytesIO
from pathlib import Path

ANNEX_B_URL = (
    "https://www.cyber.gc.ca/sites/default/files/cyber/publications/"
    "Annex%20B%20CCCS%20MEDIUM%20Cloud%20Profile%20Recommendations.xlsx"
)
NS = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
SHEET_NAME = "CCCS MEDIUM"
ID_RE = re.compile(r"[A-Z]{2}-\d+(\(\d+\))?")

FAMILIES = OrderedDict([
    ("AC", "Access Control"), ("AT", "Awareness and Training"), ("AU", "Audit and Accountability"),
    ("CA", "Security Assessment and Authorization"), ("CM", "Configuration Management"),
    ("CP", "Contingency Planning"), ("IA", "Identification and Authentication"),
    ("IR", "Incident Response"), ("MA", "Maintenance"), ("MP", "Media Protection"),
    ("PE", "Physical and Environmental Protection"), ("PL", "Planning"), ("PS", "Personnel Security"),
    ("RA", "Risk Assessment"), ("SA", "System and Services Acquisition"),
    ("SC", "System and Communications Protection"), ("SI", "System and Information Integrity"),
])


def load(source):
    if re.match(r"https?://", source):
        req = urllib.request.Request(source, headers={"User-Agent": "Mozilla/5.0 (itsg-assessment build_profile.py)"})
        with urllib.request.urlopen(req, timeout=60) as resp:
            return zipfile.ZipFile(BytesIO(resp.read()))
    return zipfile.ZipFile(source)


def sheet_rows(z):
    strings = [
        "".join(t.text or "" for t in si.iter("{%s}t" % NS["m"]))
        for si in ET.fromstring(z.read("xl/sharedStrings.xml")).findall("m:si", NS)
    ]
    wb = ET.fromstring(z.read("xl/workbook.xml"))
    names = [s.get("name") for s in wb.find("m:sheets", NS)]
    if SHEET_NAME not in names:
        sys.exit(f"sheet {SHEET_NAME!r} not found; sheets are {names}")
    path = f"xl/worksheets/sheet{names.index(SHEET_NAME) + 1}.xml"
    for row in ET.fromstring(z.read(path)).iter("{%s}row" % NS["m"]):
        cells = {}
        for c in row.findall("m:c", NS):
            col = re.match(r"[A-Z]+", c.get("r")).group()
            v = c.find("m:v", NS)
            if v is not None:
                cells[col] = strings[int(v.text)] if c.get("t") == "s" else v.text
        yield cells


def main():
    here = Path(__file__).resolve().parent.parent
    source = sys.argv[1] if len(sys.argv) > 1 else ANNEX_B_URL
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else here / "references" / "cccs-medium-profile.md"
    out_json = Path(sys.argv[3]) if len(sys.argv) > 3 else here / "assets" / "cccs-medium-controls.json"

    rows = list(sheet_rows(load(source)))
    header = rows[1]
    expected = {
        "A": "ID", "C": "Class", "D": "Title", "E": "Definition", "F": "Supplemental Guidance",
        "G": "CCCS Medium Profile for Cloud", "K": "IaaS / PaaS",
    }
    for col, name in expected.items():
        if (header.get(col) or "").strip() != name:
            sys.exit(f"unexpected column {col}: {header.get(col)!r}, expected {name!r}; spreadsheet layout changed")

    controls = []
    full = []
    for r in rows[2:]:
        cid = (r.get("A") or "").strip()
        if not cid or (r.get("G") or "").strip().upper() != "X":
            continue
        if not ID_RE.fullmatch(cid):
            sys.exit(f"unparseable control id {cid!r}")
        title = " ".join((r.get("D") or "").split()).replace("|", "/")
        client = "Yes" if (r.get("K") or "").strip().upper() == "X" else "No"
        controls.append((cid, title, (r.get("C") or "").strip(), client))
        full.append({
            "id": cid,
            "title": " ".join((r.get("D") or "").split()),
            "class": (r.get("C") or "").strip(),
            "client_iaas_paas": client == "Yes",
            "definition": r.get("E") or "",
            "guidance": r.get("F") or "",
        })

    unknown = {c[0][:2] for c in controls} - FAMILIES.keys()
    if unknown:
        sys.exit(f"unknown families {sorted(unknown)}")

    lines = [
        "# CCCS Medium Cloud Profile — Control Catalogue",
        "",
        "Generated by `scripts/build_profile.py` from ITSP.50.103 Annex B (`CCCS MEDIUM` sheet). Do not edit by hand.",
        "",
        f"{len(controls)} controls including enhancements.",
        "**Client IaaS/PaaS** = `Yes` when Annex B assigns the control to the client for IaaS/PaaS consumption; `No` means the CSP alone carries it.",
        "",
    ]
    for fam, name in FAMILIES.items():
        fam_rows = [c for c in controls if c[0].startswith(fam + "-")]
        if not fam_rows:
            continue
        lines += [f"## {fam} — {name}", "", "| ID | Title | Class | Client IaaS/PaaS |", "|---|---|---|---|"]
        lines += [f"| {cid} | {title} | {cls} | {client} |" for cid, title, cls, client in fam_rows]
        lines.append("")
    out.write_text("\n".join(lines))
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(json.dumps({"source": "ITSP.50.103 Annex B, CCCS MEDIUM sheet", "controls": full}, indent=1, ensure_ascii=False) + "\n")
    print(f"wrote {out} and {out_json} ({len(controls)} controls)")


if __name__ == "__main__":
    main()
