#!/usr/bin/env bash
# Pre-mount git-config scrub (R2.9, T22, criterion 6) -- HOST-SIDE, run BEFORE `docker compose up`.
#
# R2.9 says the `credential.helper` entry "is removed FIRST". This script is what makes that
# ordering literal: it reads the operator's own gitconfig on the host, writes a filtered artifact
# into compose/generated/gitconfig.d/, and that generated directory -- never the operator's file --
# is what compose/overrides/host-gitconfig.yaml mounts `:ro` at /run/gitconfig.
#
# The control is that the material is not there, not that something inside the container declines
# to use it. A compromised agent has no unfiltered copy to read, because no unfiltered copy ever
# crosses the boundary.
#
# THREE things are removed, not one:
#
#   credential.helper   R2.9's literal requirement. Every subsection too -- a
#                       [credential "https://github.com"] block carries its own helper.
#   include.path        An include is a POINTER. Removing only the literal helper key would
#   includeIf.*         satisfy R2.9 in letter and defeat it in fact: the included file is one
#                       this solution never mounts, so inside the container the pointer either
#                       dangles or -- worse, if the operator's include path happens to resolve
#                       on the state volume -- re-introduces a helper the scrub just removed.
#
# Includes are NOT flattened before filtering. `git config --file` leaves include directives
# unprocessed by default, and that is the behaviour wanted here: flattening would inline the
# contents of files the operator never asked to share into the artifact that does get mounted.
#
# Usage:
#   bash scripts/scrub-gitconfig.sh [source-gitconfig]
#
# Defaults to $GIT_CONFIG_GLOBAL, else ~/.gitconfig. A missing source is not an error -- it
# produces a valid empty artifact, so `mounts.host_git_config: true` works on a host that has
# no global gitconfig at all.
set -euo pipefail

SOLUTION_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$SOLUTION_ROOT/compose/generated/gitconfig.d"
OUT_FILE="$OUT_DIR/.gitconfig"

SRC="${1-${GIT_CONFIG_GLOBAL-$HOME/.gitconfig}}"

mkdir -p "$OUT_DIR"
chmod 700 "$SOLUTION_ROOT/compose/generated" "$OUT_DIR"

if [ ! -f "$SRC" ]; then
  echo "scrub-gitconfig: no source at $SRC -- writing an empty scrubbed config" >&2
  printf '%s\n' \
    '# Generated by scripts/scrub-gitconfig.sh (R2.9). Do not edit; do not commit.' \
    '# Source did not exist on the host at scrub time.' \
    > "$OUT_FILE"
  chmod 600 "$OUT_FILE"
  exit 0
fi

# Work on a copy. The operator's file is only ever READ.
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
cp "$SRC" "$TMP"

# `git config --file` does not follow include directives, so --name-only lists exactly the keys
# written in this file. --unset-all/--remove-section exit 5 when the key or section is absent,
# which is the normal case, not a failure.
#
# Every match below is CASE-INSENSITIVE, and that is load-bearing rather than defensive: git
# normalizes section names to lower case on output, so `[includeIf "gitdir:~/work/"]` is listed
# as `includeif.gitdir:~/work/.path`. A case-sensitive `includeIf` pattern matches nothing, the
# section survives the scrub, and -- because the same pattern is used in the self-check below --
# the script reports success while shipping the directive. Observed, not hypothesized.
list_keys() {
  git config --file "$TMP" --list --name-only 2>/dev/null || true
}

# 1. credential.helper, in the bare section and in every subsection.
while IFS= read -r key; do
  [ -n "$key" ] || continue
  git config --file "$TMP" --unset-all "$key" || true
done < <(list_keys | grep -Ei '^credential\.(.*\.)?helper$' || true)

# 2. include.path -- every value.
git config --file "$TMP" --unset-all include.path || true

# 3. includeIf.<condition> -- remove the whole section, condition and all.
#
# Done TEXTUALLY rather than with `git config --remove-section`, because the section name cannot
# be recovered from the flattened key list: --name-only lower-cases the section (`includeif.…`)
# while --remove-section demands the ORIGINAL case (`includeIf.…`) and exits 128 on the
# lower-cased form. Reconstructing the case from a key is guesswork; deleting the block is not.
# A section runs from its header to the line before the next header, which is also the only
# reading under which a condition with an odd subsection can never be half-removed.
awk '
  /^[[:space:]]*\[/ {
    skip = (tolower($0) ~ /^[[:space:]]*\[[[:space:]]*includeif([[:space:]]|\]|")/) ? 1 : 0
    if (skip) next
  }
  !skip
' "$TMP" > "$TMP.noinc"
mv "$TMP.noinc" "$TMP"

# Drop a now-empty [credential] / [include] header rather than shipping a dangling section.
git config --file "$TMP" --list --name-only >/dev/null 2>&1 || {
  echo "scrub-gitconfig: FAILED -- scrubbed config is not parseable by git" >&2
  exit 1
}

{
  printf '%s\n' \
    '# Generated by scripts/scrub-gitconfig.sh (R2.9, T22). Do not edit; do not commit.' \
    "# Source: $SRC" \
    '# Removed: credential.helper (all subsections), include.path, includeIf.*' \
    '#' \
    '# Mounted :ro at /run/gitconfig. `git config --global` writes FAIL inside the container by' \
    '# design -- see README.md, "Host git configuration".'
  cat "$TMP"
} > "$OUT_FILE"
chmod 600 "$OUT_FILE"

# Self-verification (criterion 6 asserts these inside the container; failing here is cheaper).
# The artifact is checked, not the intent.
fail=0

remaining_helper="$(git config --file "$OUT_FILE" --list --name-only 2>/dev/null \
  | grep -Eic '^credential\.(.*\.)?helper$' || true)"
if [ "$remaining_helper" -ne 0 ]; then
  echo "scrub-gitconfig: FAILED -- $remaining_helper credential.helper key(s) survived the scrub" >&2
  fail=1
fi

remaining_include="$(git config --file "$OUT_FILE" --list --name-only 2>/dev/null \
  | grep -Eic '^(include\.path$|includeif\.)' || true)"
if [ "$remaining_include" -ne 0 ]; then
  echo "scrub-gitconfig: FAILED -- $remaining_include include directive(s) survived the scrub" >&2
  fail=1
fi

if [ "$fail" -ne 0 ]; then
  rm -f "$OUT_FILE"
  exit 1
fi

echo "scrub-gitconfig: wrote $OUT_FILE (credential.helper, include.path, includeIf removed)"
